### ISSUE TITLE
Weight matrix generation

### ISSUE THREAD

**Issue by zbarni** [INM-6/lif_meanfield_tools#25]
Hello! This is probably more of a suggestion.. when defining a more complex network with multiple populations,  it's not really obvious that the weight matrix generation assumes an alternating definition of excitatory and inhibitory populations.. also, the current version (as far as I can tell) doesn't support passing a precomputed weight matrix to the `Network` class. Is there a clean way manually define a weight matrix that doesn't interfere with the hash computed on the parameters?

**Comment by moritzlayer** [comment]
This is resolved in v1.0 (see branch). We are currently preparing a new repository for this. In the new version it will be possible to define your own network and passing the weight matrix directly is no problem anymore.
