### ISSUE TITLE
Fully vectorized and numerically stable Siegert implementation

### ISSUE THREAD

**Issue by AlexVanMeegen** [INM-6/lif_meanfield_tools#51]
Hey!

I had to think about the numerics of the siegert for another project and had an idea which seems to work pretty well. In particular, it is straightforward to implement it fully vectorized, i.e. to compute the rate for multiple mu and sigma at once. Briefly, the idea is to use the scaled complementary error function erfcx(s), here are the details: [siegert_numerics.pdf](https://github.com/INM-6/lif_meanfield_tools/files/5421726/siegert_numerics.pdf).

@mhelias  had a look and did not spot any obvious flaw. I also asked @tomtetzlaff for his opinion, I'll report once he got back to me.

I have an implementation but I cannot upload it here. Most willing to prepare a PR if this is of interest, but I need help in order not to break the structure around it.

Cheers,
Alex

**Comment by AlexVanMeegen** [comment]
PS: The current implementation is documented [here](https://www.frontiersin.org/articles/10.3389/fninf.2017.00034/full#h10).

**Comment by AlexVanMeegen** [comment]
PPS: Also proposed this for the `siegert_neuron` in NEST in [this issue](https://github.com/nest/nest-simulator/issues/1811), although of course the benefit of the vectorization does not make such a big difference there.

**Comment by AlexVanMeegen** [comment]
PPPS: [This](https://github.com/INM-6/lif_meanfield_tools/blob/080f523f25f72fbd5567295e4dadd1bbec4103fc/lif_meanfield_tools/meanfield_calcs.py#L109) is the for loop that one could get rid of using the vectorization.

**Comment by AlexVanMeegen** [comment]
Got feedback from @tomtetzlaff; he also approves and supports the idea to incorporate this here.

**Comment by jhnnsnk** [comment]
@AlexVanMeegen This sounds like a really good idea, thanks. Yes, it would be great if you could prepare a PR. Maybe a test comparing the results of the two different approaches could also be useful.

**Comment by AlexVanMeegen** [comment]
PR for the code (quick & dirty) is there. No tests yet.

**Comment by moritzlayer** [comment]
Merged #56
