### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by AlexVanMeegen** [INM-6/lif_meanfield_tools#54]
My linter (flake8) complains about PEP8 violations, e.g. unused imports, missing blank lines, line continuations, multiple spaces, ... Is this intentional? Do you use another code style guide?

**Comment by moritzlayer** [comment]
No, it is definitely not on purpose, but, unfortunately, when we transferred the code from the old repository, we didn't use a linter. I am fixing this, together with the failing tests, in the pull-request I am currently preparing. But, I wanted to wait with this, until our test suite is merged completely.

**Comment by AlexVanMeegen** [comment]
I see - that seems to be a massive PR!
