### ISSUE TITLE
Loss of significance in nu0_fb433

### ISSUE THREAD

**Issue by AlexVanMeegen** [INM-6/lif_meanfield_tools#58]
[nu0_fb433](https://github.com/INM-6/lif_meanfield_tools/blob/1be061878429b05f9ba1b89c9afaa9f8a20f9f68/lif_meanfield_tools/aux_calcs.py#L76) seems dangerous to me from a numerical point of view. It essentially contains the problems that led me to #51.

Here is why I think it is dangerous:
1. `Phi(s)` is by itself already problematic: it contains an interplay of `exp(s**2)` and `1 + erf(s)`. For very negative `s << 0`, the latter [behaves like](https://en.wikipedia.org/wiki/Error_function#Asymptotic_expansion) `exp(-s**2)` which precisely cancels the `exp(s**2)`. However, the sum `1 + erf(s)` potentially leads to a loss of accuracy and could mask this nice cancelation.
2. A difference `Phi(x_th) - Phi(x_r)` is calculated. For large `s >> 0`, `Phi(s)` behaves like `exp(s**2)`. Thus, already for `s = 10` one subtracts two number of order `1e43` which will surely lead to a loss of significance.
3. A product `dPhi * r**2` is calculated. Due to 1. and 2., the dPhi has a reduced precision for large `s >> 0`. This case corresponds to strong inhibitory mean input since `x_th` or `x_r` are proportional to `-mu`. Thus, one multiplies the dPhi, which behaves like `exp(s**2)`, with the rate `r` which should be very small.

All of this can be fixed with ideas similar to the ones in #51: one essentially extracts the leading order exponential contributions to `dPhi * r**2`. If you think #56 is fine, I could prepare a corresponding PR since I implemented this already for another project (a multi-area model type network) where precisely this problem made my numerics blow up.

Beyond this issue, just for my curiosity: why is `nu0_fb433` used instead of `nu0_fb`?

**Comment by moritzlayer** [comment]
Yes, it would be great if you could open another PR for this. I still need to check #56 though. 

I guess there is no proper reason for choosing `nu0_fb433` over `nu0_fb`. This decision has been inherited from the old repository. But they should be equivalent up to first order in <img src="https://render.githubusercontent.com/render/math?math=\sqrt{\tau_s/\tau_m}">. We have to make the same arbitrary decision when it comes to the transfer function, and the two different methods do give slightly different results. If you want to know more about that, @essink has investigated that in more detail. For the transfer function we decided to enable choosing the method (taylor or shift), which is included in #57.

**Comment by AlexVanMeegen** [comment]
Thanks for the explanation, this was precisely what I was wondering about. Due to the above numerical reasons, I would (currently) argue in favor of `nu0_fb`, but that's just my two cents.

I'll wait with the PR until you checked #56 because it would build on this.

**Comment by moritzlayer** [comment]
Resolved by #60
