### ISSUE TITLE
Converting weights pA -> mV

### ISSUE THREAD

**Issue by zbarni** [INM-6/lif_meanfield_tools#59]
I was wondering if the computation of the synaptic efficacies, `J`, from the PSC peaks `w`, is correct? For the `iaf_psc_exp` model with `C_m=250., tau_syn_ex=2., tau_m=20.`, the EPSP amplitude following a spike with weight `w=32.78` is close to `0.2 mV`. 
However, the tool computes `J = 0.25824`.

In `network.py`, lines 158-160 show
```
        # convert weights in pA (current) to weights in mV (voltage)
        tau_s_div_C = self.network_params['tau_s'] / self.network_params['C']
        derived_params['j'] = (tau_s_div_C * self.network_params['w']).to(ureg.mV)
```
Where does this formula come from? Shouldn't the equation be as [here](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007790#sec031) (sup. table 1)?   Converting current weights to EPSP amplitudes is probably model dependent, but I assumed the tool was originally developed for the current-based synapses with exponential decay.

**Comment by tomtetzlaff** [comment]
I agree. If J and w are supposed to denote the  PSP and PSC maxima, respectively, the conversion needs to be done using the equation in [Bachmann et al., 2020](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007790#sec031).

**Comment by jhnnsnk** [comment]
The formula for unit conversion is also given in "Appendix G: Physical Units" of [Senk et al. (2020)](https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.2.023174#fulltext).
 We could potentially add a comment to explain the difference.

**Comment by zbarni** [comment]
Thanks for clarifying this! It was a confusion on my side, I thought J always corresponds to the PSP amplitude. Maybe a comment on those lines would be helpful for the future, though.
Closing the issue.
